// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9FmR-VbWQ8GsZVsCWex81njbSn6Qv3nI',
    appId: '1:908438314725:web:d12bcd44d5321bbb737e0c',
    messagingSenderId: '908438314725',
    projectId: 'shca-89db8',
    authDomain: 'shca-89db8.firebaseapp.com',
    storageBucket: 'shca-89db8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBD3gdnixpuMZXMpFMaB-chqXURlGfU5I',
    appId: '1:908438314725:android:1048465d0f6e4b8a737e0c',
    messagingSenderId: '908438314725',
    projectId: 'shca-89db8',
    storageBucket: 'shca-89db8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy62qO6sEMi8PGx83AwN0IxFjb3XakoF0',
    appId: '1:908438314725:ios:a0d4b42a9af961a9737e0c',
    messagingSenderId: '908438314725',
    projectId: 'shca-89db8',
    storageBucket: 'shca-89db8.appspot.com',
    iosClientId: '908438314725-7kj44ed1prs25fonsl5u8m0mtr976alo.apps.googleusercontent.com',
    iosBundleId: 'com.example.shca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy62qO6sEMi8PGx83AwN0IxFjb3XakoF0',
    appId: '1:908438314725:ios:a0d4b42a9af961a9737e0c',
    messagingSenderId: '908438314725',
    projectId: 'shca-89db8',
    storageBucket: 'shca-89db8.appspot.com',
    iosClientId: '908438314725-7kj44ed1prs25fonsl5u8m0mtr976alo.apps.googleusercontent.com',
    iosBundleId: 'com.example.shca',
  );
}
